apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-banking-app
  namespace: argocd
spec:
  project: gitops-project
  source:
    repoURL: https://github.com/your-repo/gitops-aks-banking
    targetRevision: HEAD
    path: k8s-manifests/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
